### ISSUE TITLE
SYSTEM: Evaluating future failed. Trying to load olympics data from *local* express server.

### ISSUE THREAD

**Issue by LuisFX** [the-gamma/thegamma-sample-web#2]
Hi, we are trying to setup the sample project to load custom data. The first thing that we are trying to do is to serve the same olympics json data from the simple express server in the project.

We first:

```bash
curl https://thegamma-services.azurewebsites.net/pdata/olympics --output olympics.json
```

Next, we added the following code to server.js (and verified the route works):

```javascript
var olympicsData = JSON.parse(fs.readFileSync('./providers/olympics.json', 'utf8')); /* Inside the get function */

app.set('json spaces', 0); // Make Express pass '0' as the 3rd argument to `JSON.stringify()` to minify data

app.get('/olympics', function(req, res) {
  res.json(olympicsData);
});
```

Lastly, we updated the provider route:

```javascript
var services = "http://localhost:8089/"    
var graphServices = "https://thegamma-graph-service.azurewebsites.net/";
      
var providers = 
  g.providers.createProviders({ 
    "libraries": g.providers.library("/node_modules/thegamma-script/dist/libraries.json"),
    "olympics": g.providers.pivot(services + "olympics") });
```

This is the output from the console:

<img width="1069" alt="Screen Shot 2022-03-07 at 5 36 46 AM" src="https://user-images.githubusercontent.com/1130772/157045203-5183ed3e-c663-48ef-94a2-c4fb76e2aa99.png">

**Comment by LuisFX** [comment]
It was our mistake making wrong assumptions. The "services" project is what we'll be focusing on next.

**Comment by tpetricek** [comment]
Hi! It's very cool you are interested in this project - I have not been very active in the project, but I'm still interested in doing this and helping anyone who wants to use it! Please let me know how it's going - feel free to drop me an email at tomas@tomasp.net if you wanted to chat or anything!
